/**
 * Seed script: populate prompts.json with all prompts from mcp-prompts-library.md
 * Run: node scripts/seed_prompts.js
 */
const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(__dirname, '../data/prompts/prompts.json');

const data = JSON.parse(fs.readFileSync(DB_PATH, 'utf8'));
const existing = new Set(data.prompts.map(p => p.slug));
const maxId = Math.max(...data.prompts.map(p => p.id));

const newPrompts = [
  // Memory Management
  {title:'Quick Memory Keyword Search',category:'Memory Management',description:'Execute memory_search with a user-specified query and return all matching memory entries with timestamps and relevance scores.',prompt_text:'Execute memory_search with query: "user specified topic" and return all matching memory entries with timestamps and relevance scores.',tools:['memory_search'],setup_steps:['Ensure memory_search tool is configured','Identify the keyword or topic to search','Call memory_search with the query'],trigger:'memory_search'},
  {title:'Retrieve Specific Memory Entry',category:'Memory Management',description:'Fetch a complete memory entry by its unique ID, including all embedded context and metadata.',prompt_text:'Execute memory_get with memory_id: "user specified ID" and display the full content including all embedded context and metadata.',tools:['memory_get'],setup_steps:['Locate the memory ID to retrieve','Call memory_get with the specified memory_id'],trigger:'memory_get'},
  {title:'Setup Semantic Memory Recall',category:'Memory Management',description:'Search for foundational memory entries and retrieve them to build a semantic context vector for improved recall.',prompt_text:'Execute memory_search with query: "core concepts preferences goals" and store the top 5 results, then execute memory_get on each to build a semantic context vector for recall.',tools:['memory_search','memory_get'],setup_steps:['Define the core concepts query','Execute memory_search','Loop through results with memory_get','Build semantic context vector'],trigger:'memory_search'},
  {title:'Log Memory Access Event',category:'Memory Management',description:'Append a timestamped access log entry to track when and how memory files are being accessed.',prompt_text:'Execute exec to append timestamp and access details to /home/user/memory/access_log.jsonl in format: {"timestamp": "ISO8601", "action": "read/write/search", "memory_id": "..."}',tools:['exec'],setup_steps:['Identify the memory action being performed','Execute exec to append the log entry'],trigger:'exec'},
  {title:'Build Knowledge Index',category:'Memory Management',description:'Scan a knowledge directory, index each document topics, and create a searchable JSON index.',prompt_text:'Execute exec to list all .md files in /home/user/knowledge/, then loop through each file executing memory_search to index topics, then create /home/user/memory/knowledge_index.json.',tools:['exec','memory_search'],setup_steps:['List all markdown files in the knowledge directory','Index each document with memory_search','Create the knowledge_index.json file'],trigger:'memory_search'},
  {title:'Cross-Reference Memory Search',category:'Memory Management',description:'Perform two memory searches and identify overlapping concepts between topics.',prompt_text:'Execute memory_search with query: "user topic A", capture results, then execute memory_search with query: "user topic B", then compare both results and output common links to /home/user/memory/cross_ref.md.',tools:['memory_search','exec'],setup_steps:['Execute first memory_search for topic A','Execute second memory_search for topic B','Compare and identify overlaps','Write cross-reference to file'],trigger:'memory_search'},
  {title:'Export Memory Backup',category:'Memory Management',description:'Create a compressed backup of all memory files and verify the search index remains functional.',prompt_text:'Execute exec to create /home/user/memory/backup-YYYY-MM-DD.tar.gz containing all files from /home/user/memory/, then verify indexing integrity with memory_search.',tools:['exec','memory_search'],setup_steps:['Create compressed tar archive of memory directory','Verify search index integrity with wildcard search'],trigger:'exec'},
  {title:'Clean Expired Memory Entries',category:'Memory Management',description:'Identify outdated memory entries older than 90 days and archive them to free up active memory.',prompt_text:'Execute memory_search with query: "expired OR obsolete" to find old entries, then move files older than 90 days to /home/user/memory/archive/.',tools:['memory_search','exec'],setup_steps:['Search for expired or obsolete entries','Retrieve details of each old entry','Move files older than 90 days to archive'],trigger:'memory_search'},
  {title:'Inject Context from Memory',category:'Memory Management',description:'Find project-relevant historical context and inject it into a working file for the current session.',prompt_text:'Execute memory_search with query: "current project context", retrieve top result with memory_get, then append relevant context to /home/user/current_context.md for active session.',tools:['memory_search','memory_get','exec'],setup_steps:['Search for current project context','Retrieve top result with memory_get','Append context to current_context.md'],trigger:'memory_search'},
  {title:'Update Knowledge Base Entry',category:'Memory Management',description:'Retrieve an existing knowledge entry, modify it, and save the updated version to memory.',prompt_text:'Execute memory_get with memory_id: "user specified ID", then create updated version with new information, then write to /home/user/memory/knowledge/user-topic.md.',tools:['memory_get','exec'],setup_steps:['Retrieve existing knowledge entry','Create updated version with new information','Write updated entry to knowledge directory'],trigger:'memory_get'},

  // Research & Writing
  {title:'Deep Web Research on Topic',category:'Research & Writing',description:'Conduct comprehensive web research on any topic using multiple search queries and compile findings into a structured research document.',prompt_text:'Conduct comprehensive web research on [INSERT TOPIC] using web_search. Search for recent articles, academic sources, industry reports, and expert opinions. Compile findings into a structured research document with key insights, statistics, and source links.',tools:['web_search','write'],setup_steps:['Define the research topic','Perform multiple web searches on different angles','Compile findings into a structured document'],trigger:'web_search'},
  {title:'Article Summarization and Key Points',category:'Research & Writing',description:'Fetch an article from a URL, analyze it, and extract the main thesis, key points, statistics, and conclusions.',prompt_text:'Fetch the article at [INSERT URL] using web_fetch, then analyze and summarize the content. Extract: 1) Main thesis/argument, 2) Key supporting points (minimum 5), 3) Important statistics or data, 4) Conclusions.',tools:['web_fetch'],setup_steps:['Provide the article URL to fetch','Model analyzes and extracts key points','Structured summary is generated'],trigger:'web_fetch'},
  {title:'AI Content Generation for Blog Post',category:'Research & Writing',description:'Generate a complete SEO-optimized blog post on any topic using MiniMax M2.5, including title, introduction, body sections, and conclusion.',prompt_text:'Using miniMax/M2.5, generate a complete blog post on [INSERT TOPIC]. Requirements: engaging title, introduction with hook, 5-7 body sections with subheadings, practical examples, and a compelling conclusion. Target word count: [INSERT NUMBER] words. Include SEO-optimized meta description.',tools:['minimax/M2.5'],setup_steps:['Define topic and target word count','Model generates full blog post','Review and publish'],trigger:'minimax/M2.5'},
  {title:'Fact-Check and Verify Claims',category:'Research & Writing',description:'Verify claims using authoritative sources with at least 3 cross-references per claim and confidence levels.',prompt_text:'Fact-check the following claims: [INSERT CLAIMS]. Use web_search to find authoritative sources, then verify each claim as TRUE, FALSE, or PARTIALLY TRUE with supporting evidence. Cross-reference with at least 3 sources per claim.',tools:['web_search','write'],setup_steps:['List claims to fact-check','Model searches authoritative sources','Cross-reference minimum 3 sources per claim','Compile verification report'],trigger:'web_search'},
  {title:'Multi-Source Research Synthesis',category:'Research & Writing',description:'Research a complex question across multiple sources and synthesize findings into a comprehensive brief with conflicting viewpoints.',prompt_text:'Search for information on [INSERT RESEARCH QUESTION] using web_search with multiple search queries. Fetch the top 5 most relevant articles using web_fetch. Synthesize findings into a comprehensive research brief with conflicting viewpoints, consensus points, and gaps in research.',tools:['web_search','web_fetch'],setup_steps:['Define the research question','Perform multiple search queries','Fetch top 5 articles','Synthesize into a comprehensive brief'],trigger:'web_search'},
  {title:'Content Outline Generation',category:'Research & Writing',description:'Create a detailed content outline including title options, target audience, sections, word counts, and source recommendations.',prompt_text:'Create a detailed content outline for [INSERT TOPIC/ARTICLE TYPE]. Include: title options, target audience, main sections with subsections, key points per section, suggested word count per section, and recommended sources to cite.',tools:['minimax/M2.5'],setup_steps:['Define topic and article type','Model generates comprehensive outline','Save as planning document'],trigger:'minimax/M2.5'},
  {title:'Competitor Analysis via Web Research',category:'Research & Writing',description:'Identify and analyze top competitors, their content strategy, positioning, and find content gaps you can exploit.',prompt_text:'Research competitors in [INSERT INDUSTRY/NICHE]. Use web_search to identify top 5 competitors, then use web_fetch to analyze their content strategy, blog topics, and unique positioning. Compile into a competitive analysis report.',tools:['web_search','web_fetch'],setup_steps:['Define industry or niche','Identify top 5 competitors','Analyze content strategy and positioning','Compile competitive analysis report'],trigger:'web_search'},
  {title:'Automated Citation and Bibliography Generator',category:'Research & Writing',description:'Research a topic, find credible sources, and format them into proper APA citations with a complete bibliography.',prompt_text:'Research [INSERT TOPIC] and find at least 8 credible sources using web_search. For each source, extract: author, title, publication date, URL, and relevant quotes/key points. Format citations in APA style.',tools:['web_search'],setup_steps:['Define research topic','Find at least 8 credible sources','Extract citation details','Format in APA style'],trigger:'web_search'},
  {title:'Memory-Enhanced Research Workflow',category:'Research & Writing',description:'Combine prior research from memory with fresh web searches to build comprehensive updated research documents.',prompt_text:'Search memory for any previous research or notes on [INSERT TOPIC] using memory_search. Then conduct fresh web research on any gaps using web_search. Synthesize old and new findings into an updated research document. Tag and save to memory for future retrieval.',tools:['memory_search','web_search'],setup_steps:['Search memory for prior research','Identify gaps in existing knowledge','Conduct fresh web research','Synthesize and save to memory'],trigger:'memory_search'},
  {title:'Article Quality Audit and Improvement',category:'Research & Writing',description:'Analyze an article for readability, SEO, factual accuracy, structure, and engagement then rewrite the weakest sections.',prompt_text:'Fetch the article at [INSERT URL] using web_fetch. Analyze for: readability score, SEO elements, factual accuracy, structure flow, and engagement factors. Provide specific improvement recommendations and rewrite the top 2 weakest sections.',tools:['web_fetch'],setup_steps:['Provide article URL','Model analyzes multiple quality dimensions','Provides recommendations and rewrites weakest sections'],trigger:'web_fetch'},
  {title:'Industry Trend Analysis Report',category:'Research & Writing',description:'Track and analyze current industry trends with impact assessments, key drivers, and future predictions.',prompt_text:'Research current trends in [INSERT INDUSTRY] for [INSERT TIME PERIOD]. Use web_search to find trend reports, industry news, and expert predictions. Fetch top 5 trend articles. Create a trend analysis report with: emerging trends, impact assessment, key drivers, and future predictions.',tools:['web_search','web_fetch'],setup_steps:['Define industry and time period','Find trend reports and expert predictions','Fetch top trend articles','Create structured trend report'],trigger:'web_search'},
  {title:'Automated Writing Draft from Research',category:'Research & Writing',description:'Transform research data into a polished, publication-ready article with proper structure, flow, and formatting.',prompt_text:'Using the research data in [INSERT FILENAME], generate a polished article using miniMax/M2.5. Follow this structure: compelling headline, 150-word introduction, 6 body paragraphs with transitions, and 100-word conclusion. Include 2-3 subheadings and add a call-to-action.',tools:['read','minimax/M2.5'],setup_steps:['Prepare research data file','Define article structure requirements','Model generates publication-ready draft'],trigger:'minimax/M2.5'},

  // Coding & Automation
  {title:'Spawn Python Coding Agent',category:'Coding & Automation',description:'Create a new autonomous Python coding agent that builds automation scripts without asking for confirmation.',prompt_text:'Use sessions_spawn to create a new coding-agent session named python-automation with the coding-agent skill. Then use sessions_send to tell it to create a Python script that automates a defined task with error handling and logging.',tools:['sessions_spawn','sessions_send'],setup_steps:['Define the automation task','Spawn the coding agent','Agent autonomously builds the script'],trigger:'sessions_spawn'},
  {title:'Run Automated Bash Script',category:'Coding & Automation',description:'Execute a bash script that backs up recent files and runs deployment automatically without confirmation prompts.',prompt_text:'Use exec to execute a bash script that finds recent Python files, backs them up, runs deployment, and logs the completion without requiring user confirmation at any step.',tools:['exec'],setup_steps:['Define the bash script to run','Execute with exec tool','Script runs without confirmation'],trigger:'exec'},
  {title:'Automated Code Review via GitHub',category:'Coding & Automation',description:'Retrieve PR details from GitHub and run pylint on all Python files, outputting a JSON review report.',prompt_text:'Use gh to run an automated code review. Then use exec to run pylint on all Python files in the workspace, outputting a JSON review report.',tools:['gh','exec'],setup_steps:['Ensure gh CLI is authenticated','Define codebase path','Model runs code review and pylint'],trigger:'gh'},
  {title:'Schedule Daily Cron Job',category:'Coding & Automation',description:'Schedule a cron job to run an automation script daily at a specified time with automatic logging.',prompt_text:'Use cron to create a daily automation task and confirm the cron is active. The cron daemon will automatically execute this task without any further intervention.',tools:['cron'],setup_steps:['Define the cron schedule','Provide the script path','Activate cron job'],trigger:'cron'},
  {title:'Automated Git Commit and Push',category:'Coding & Automation',description:'Automatically stage all changes, commit with a timestamp, and push to the current branch on GitHub.',prompt_text:'Use gh to run: gh repo set-default and then git add -A, git commit with a timestamp, and git push to the current branch without prompting for confirmation.',tools:['gh','exec'],setup_steps:['Ensure gh CLI is authenticated','Model commits and pushes changes'],trigger:'gh'},
  {title:'Multi-Agent Parallel Code Generation',category:'Coding & Automation',description:'Launch three parallel coding agents simultaneously to develop different project components, dramatically reducing development time.',prompt_text:'Use subagents to spawn 3 concurrent coding agents: Agent1 with Python skill, Agent2 with Node skill, Agent3 with Go skill. Wait for all to complete and use sessions_list to verify.',tools:['subagents','sessions_list'],setup_steps:['Define the three tasks for parallel agents','Spawn all three agents simultaneously','Wait for completion and verify results'],trigger:'subagents'},
  {title:'Search Codebase Memory',category:'Coding & Automation',description:'Find all stored code patterns related to a topic and retrieve detailed implementation notes from the knowledge base.',prompt_text:'Use memory_search to find all stored code patterns related to a topic. Then use memory_get to retrieve the full context of the most relevant result.',tools:['memory_search','memory_get'],setup_steps:['Define the code pattern topic to search','Execute memory_search for relevant patterns','Retrieve detailed implementation notes'],trigger:'memory_search'},
  {title:'Automated Code File Operations',category:'Coding & Automation',description:'Read configuration files and automatically generate reusable code that loads and processes them.',prompt_text:'Use filesystem to read a config file and write a script that loads and processes that configuration automatically.',tools:['read','write'],setup_steps:['Provide config file path','Model reads config and generates processing code','Script is written automatically'],trigger:'read'},
  {title:'Install Dependencies and Run Tests',category:'Coding & Automation',description:'Silently install npm dependencies, run the test suite in CI mode, and display a summary of results.',prompt_text:'Use exec to install npm dependencies silently, run the test suite in CI mode outputting JSON results, and display a summary of passing/failing/skipped tests.',tools:['exec'],setup_steps:['Define workspace path and test command','Model executes install and test','Results are summarized'],trigger:'exec'},
  {title:'Web Fetch Documentation and Generate Code',category:'Coding & Automation',description:'Fetch API documentation from the web, parse it, and automatically generate a Python client library.',prompt_text:'Use web_fetch to get API documentation and then generate a Python client library based on the documented endpoints.',tools:['web_fetch','exec'],setup_steps:['Provide API documentation URL','Model fetches docs and generates client code'],trigger:'web_fetch'},
  {title:'Browser-Based UI Code Inspection',category:'Coding & Automation',description:'Navigate to a local web application, extract all JavaScript dependencies from the DOM, and save them for auditing.',prompt_text:'Use browser to navigate to a local web application and extract all script source URLs from the DOM, then save them to a dependencies file.',tools:['browser','write'],setup_steps:['Navigate to the web application','Extract all script source URLs','Save to dependencies file'],trigger:'browser'},

  // Communication & Scheduling
  {title:'Send Slack Status Update',category:'Communication & Scheduling',description:'Send a pre-composed message to a Slack channel through the sessions_send tool without asking for confirmation.',prompt_text:'Use sessions_send to send a pre-composed message to a specified Slack channel without asking for confirmation.',tools:['sessions_send'],setup_steps:['Define the channel and message','Model sends the message autonomously'],trigger:'sessions_send'},
  {title:'Schedule Tomorrow Reminder',category:'Communication & Scheduling',description:'Create a recurring daily reminder in Apple Reminders that alerts you before each scheduled time.',prompt_text:'Use apple-reminders skill to create a reminder with a specified title, time, repeat frequency, and alert before time.',tools:['apple-reminders'],setup_steps:['Define reminder title, time, and recurrence','Model creates the reminder with apple-reminders'],trigger:'apple-reminders'},
  {title:'Weekly Reminder via Cron',category:'Communication & Scheduling',description:'Add a cron job that triggers a weekly reminder at a specified time using system notifications.',prompt_text:'Use exec to add a cron job that triggers a weekly reminder on a specified day and time using system notifications.',tools:['exec','cron'],setup_steps:['Define the weekly schedule and reminder message','Model adds the cron job'],trigger:'cron'},
  {title:'Inbox Triage - Label Urgent',category:'Communication & Scheduling',description:'Spawn a dedicated session to scan your inbox, identify urgent messages based on keywords, and apply urgent labels.',prompt_text:'Use sessions_spawn to create a new inbox-triage session then use sessions_send to search email for urgent messages by keyword and label them.',tools:['sessions_spawn','sessions_send'],setup_steps:['Define urgent keyword criteria','Spawn inbox triage session','Model scans and labels urgent messages'],trigger:'sessions_spawn'},
  {title:'Summarize Discord Channel',category:'Communication & Scheduling',description:'Retrieve recent messages from a channel and generate a structured summary of key decisions, action items, and questions.',prompt_text:'Use sessions_list to list active sessions, then use sessions_send to fetch recent messages from a channel and provide a summary of key decisions, action items, and unanswered questions.',tools:['sessions_list','sessions_send'],setup_steps:['Define channel and message count','Model retrieves and summarizes messages'],trigger:'sessions_list'},
  {title:'Check Active Reminders',category:'Communication & Scheduling',description:'Query the remindctl command-line tool to display all active reminders in a structured format for review.',prompt_text:'Use exec to run: remindctl list --all --format json to display all active reminders in a structured format.',tools:['exec'],setup_steps:['Model executes the remindctl command','Active reminders are displayed'],trigger:'exec'},
  {title:'Broadcast Message to Team',category:'Communication & Scheduling',description:'Broadcast a message to multiple channels simultaneously, ensuring the team receives notifications.',prompt_text:'Use sessions_send to send a message to multiple channels simultaneously, ensuring the team receives the scheduling notification.',tools:['sessions_send'],setup_steps:['Define message and target channels','Model sends to all channels at once'],trigger:'sessions_send'},
  {title:'Schedule Focus Time Block',category:'Communication & Scheduling',description:'Create a time-blocked reminder for focused work, ensuring you receive a notification before the block begins.',prompt_text:'Use apple-reminders skill to create a reminder titled "Deep Work Block" with notes and alert before the block begins.',tools:['apple-reminders'],setup_steps:['Define focus block time and notes','Model creates the reminder'],trigger:'apple-reminders'},
  {title:'Search Communication History',category:'Communication & Scheduling',description:'Search stored communication history for relevant project notes and return the most recent matching entries.',prompt_text:'Use memory_search to query project-related communications and return the last 5 stored communications related to project planning.',tools:['memory_search'],setup_steps:['Define the search query','Model retrieves matching communications'],trigger:'memory_search'},
  {title:'Set Meeting Follow-Up Task',category:'Communication & Scheduling',description:'Create a high-priority follow-up task with a due date, ensuring you do not forget to follow up after meetings.',prompt_text:'Use apple-reminders skill to create a high-priority follow-up reminder with notes and a due date.',tools:['apple-reminders'],setup_steps:['Define follow-up task, person, and due date','Model creates high-priority reminder'],trigger:'apple-reminders'},
  {title:'Archive Old Messages',category:'Communication & Scheduling',description:'Retrieve old messages from memory, package them with a dated filename, and save them to your archives folder.',prompt_text:'Use memory_get to retrieve messages older than a specified age, then write them to an archive file with a dated filename.',tools:['memory_get','write'],setup_steps:['Define age threshold for archiving','Model retrieves and packages old messages','Files are saved with dated filename'],trigger:'memory_get'},
  {title:'Quick Message to Channel',category:'Communication & Scheduling',description:'Immediately send a deployment or status notification to a specified channel without requiring confirmation.',prompt_text:'Use message to send a status notification to a specified channel immediately without requiring any additional confirmation.',tools:['message'],setup_steps:['Define message and target channel','Model sends immediately'],trigger:'message'},

  // Monitoring & Alerts
  {title:'Setup Heartbeat Monitor for Service',category:'Monitoring & Alerts',description:'Create a cron-based heartbeat that checks your API endpoint every 5 minutes and triggers an alert if the response is not 200.',prompt_text:'Create a cron-based heartbeat monitor that checks the primary API endpoint every 5 minutes. Log the response code. If the response is not 200, trigger an alert via the message tool.',tools:['cron','exec','message'],setup_steps:['Define the API endpoint to monitor','Model creates the cron job and alert logic'],trigger:'cron'},
  {title:'Check All Services Status',category:'Monitoring & Alerts',description:'Run concurrent health checks on your web server, database, and Redis cache, and compile results into a JSON status file.',prompt_text:'Execute a system status check across all critical services. Run parallel health checks on web server, database, and Redis. Aggregate results and write the status report to a JSON file.',tools:['exec'],setup_steps:['Define services and endpoints to check','Model runs concurrent health checks','Results compiled to status file'],trigger:'exec'},
  {title:'Track API Usage Metrics',category:'Monitoring & Alerts',description:'Set up hourly API usage tracking that parses application logs and alerts if error rates exceed 5%.',prompt_text:'Set up API usage tracking by creating a monitoring script that runs hourly via cron. Extract API usage from logs and write metrics with timestamps. If errors exceed 5% threshold, trigger an alert via message.',tools:['cron','exec','memory_search','message'],setup_steps:['Define log path and error threshold','Model creates hourly cron monitoring job'],trigger:'cron'},
  {title:'Automated Health Check Pipeline',category:'Monitoring & Alerts',description:'Create a comprehensive 15-minute health check that validates your web application, database, Redis, and external dependencies.',prompt_text:'Create an automated health check pipeline that runs every 15 minutes. Check web application, database connectivity, Redis, and external dependencies. Compile all results and send a summary to the ops channel.',tools:['browser','exec','cron','message'],setup_steps:['Define health endpoint and check components','Model creates 15-minute health check pipeline'],trigger:'cron'},
  {title:'Configure Alert Threshold Monitor',category:'Monitoring & Alerts',description:'Monitor CPU and memory usage every minute and send instant notifications when thresholds are exceeded.',prompt_text:'Configure a monitoring threshold alert for CPU and memory usage. Create a cron job that runs every minute to check resource usage. If thresholds are exceeded, immediately send an alert to the on-call channel. Log all readings.',tools:['cron','exec','message'],setup_steps:['Define CPU and memory thresholds','Model creates per-minute monitoring cron'],trigger:'cron'},
  {title:'Monitor OpenClaw Session Health',category:'Monitoring & Alerts',description:'Test all OpenClaw sessions for responsiveness, identify unhealthy ones, and archive sessions older than 24 hours.',prompt_text:'Check the health of all OpenClaw sessions. Use sessions_list to retrieve all active sessions. Test responsiveness of each. Identify any sessions that do not respond within 10 seconds and log them. Archive any stale sessions older than 24 hours.',tools:['sessions_list','sessions_send','exec'],setup_steps:['Model retrieves all sessions','Test responsiveness of each','Log unhealthy and archive stale sessions'],trigger:'sessions_list'},
  {title:'Setup Disk Space Alert System',category:'Monitoring & Alerts',description:'Monitor all disk volumes every 10 minutes and automatically send critical alerts when any volume exceeds 85% capacity.',prompt_text:'Create a disk space monitoring alert system. Check disk usage on all mounted volumes. If any volume exceeds 85% usage, send a critical alert. Schedule to run every 10 minutes via cron.',tools:['exec','cron','message'],setup_steps:['Define disk usage threshold','Model creates 10-minute disk monitoring cron'],trigger:'cron'},
  {title:'Monitor Error Log Patterns',category:'Monitoring & Alerts',description:'Watch error logs for critical patterns, research potential solutions via web search, and compile a summary report with remediation suggestions.',prompt_text:'Set up automated error pattern monitoring. Use exec to watch the error log. Parse for common error patterns. For each pattern found, use web_search to look up common solutions. Compile a summary report and send it to the dev team channel.',tools:['exec','web_search','message'],setup_steps:['Define error log path','Model monitors patterns and researches solutions','Compiled report sent to dev team'],trigger:'exec'},
  {title:'Setup Uptime Verification Monitor',category:'Monitoring & Alerts',description:'Verify your service is accessible every 5 minutes by loading the page, checking for key content, and pinging the domain.',prompt_text:'Setup continuous uptime verification. Use browser to navigate to the main application URL every 5 minutes. Take a screenshot and verify the page loads correctly. Ping the domain. Log all uptime data with timestamps. If any check fails 3 consecutive times, send an uptime alert.',tools:['browser','exec','cron','message'],setup_steps:['Define main application URL','Model creates 5-minute uptime check','Alerts fire after 3 consecutive failures'],trigger:'cron'},
  {title:'Monitor Background Cron Jobs',category:'Monitoring & Alerts',description:'Scan all cron configurations and running processes to identify any jobs exceeding 1 hour of execution time.',prompt_text:'Monitor all running cron jobs and background processes. Use exec to list all cron tabs and running processes. Identify any jobs that have been running for over 1 hour and alert the ops team with details.',tools:['exec','message'],setup_steps:['Model scans all cron configurations and processes','Identifies long-running jobs','Alerts ops team'],trigger:'exec'},
  {title:'Monitor API Response Times',category:'Monitoring & Alerts',description:'Measure response times across your top 5 API endpoints and log them with millisecond precision, alerting when any endpoint exceeds 2 seconds.',prompt_text:'Track API response times continuously. Measure response times for the top 5 API endpoints. Write all timing data to a CSV file. If any endpoint exceeds 2000ms, send a slow API alert.',tools:['exec','message','cron'],setup_steps:['Define top 5 API endpoints','Model creates response time tracking','Alert on slow endpoints'],trigger:'cron'},
  {title:'Configure GitHub Status Monitor',category:'Monitoring & Alerts',description:'Monitor GitHub repository status and workflow health, checking for failing workflows and API rate limit status.',prompt_text:'Monitor GitHub repository status and workflow health. Use gh to check repository status and failing workflows. Compile a status report and send to the devops channel if any workflows failed.',tools:['gh','exec','message'],setup_steps:['Ensure gh CLI is authenticated','Model checks workflow runs and rate limits','Alerts devops on failures'],trigger:'gh'},
];

let nextId = maxId + 1;
const now = Math.floor(Date.now() / 1000);
const toAdd = [];

for (const p of newPrompts) {
  const slug = p.title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').substring(0, 60);
  if (existing.has(slug)) {
    console.log('SKIP (exists):', p.title);
    continue;
  }
  toAdd.push({
    id: nextId++,
    slug,
    title: p.title,
    category: p.category,
    description: p.description,
    prompt_text: p.prompt_text,
    tools: p.tools,
    setup_steps: p.setup_steps,
    example_output: '',
    is_staff_pick: false,
    vote_count: 0,
    created_at: now,
    updated_at: now,
  });
}

data.prompts.push(...toAdd);
fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2));
console.log('Added', toAdd.length, 'prompts. Total now:', data.prompts.length);
